version: 2
formats:
  - pdf
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
python:
  install:
    - requirements: docs/readthedocs-reqs.txt
    - method: pip
      path: .
sphinx:
  builder: html
  configuration: docs/conf.py
